# S&P 500 종목 데이터 확장 (약 400개)
# Weight: 대략적인 시가총액 (억 달러 단위)

STOCKS = [
    # --- Technology ---
    {"ticker": "AAPL", "name": "Apple", "sector": "Technology", "weight": 3400},
    {"ticker": "MSFT", "name": "Microsoft", "sector": "Technology", "weight": 3100},
    {"ticker": "NVDA", "name": "NVIDIA", "sector": "Technology", "weight": 2800},
    {"ticker": "AVGO", "name": "Broadcom", "sector": "Technology", "weight": 800},
    {"ticker": "ORCL", "name": "Oracle", "sector": "Technology", "weight": 480},
    {"ticker": "CRM", "name": "Salesforce", "sector": "Technology", "weight": 320},
    {"ticker": "AMD", "name": "AMD", "sector": "Technology", "weight": 260},
    {"ticker": "ADBE", "name": "Adobe", "sector": "Technology", "weight": 240},
    {"ticker": "CSCO", "name": "Cisco", "sector": "Technology", "weight": 210},
    {"ticker": "ACN", "name": "Accenture", "sector": "Technology", "weight": 210},
    {"ticker": "INTC", "name": "Intel", "sector": "Technology", "weight": 100},
    {"ticker": "QCOM", "name": "Qualcomm", "sector": "Technology", "weight": 190},
    {"ticker": "IBM", "name": "IBM", "sector": "Technology", "weight": 170},
    {"ticker": "TXN", "name": "Texas Inst", "sector": "Technology", "weight": 160},
    {"ticker": "NOW", "name": "ServiceNow", "sector": "Technology", "weight": 160},
    {"ticker": "AMAT", "name": "Applied Mat", "sector": "Technology", "weight": 150},
    {"ticker": "MU", "name": "Micron", "sector": "Technology", "weight": 140},
    {"ticker": "ADI", "name": "Analog Dev", "sector": "Technology", "weight": 120},
    {"ticker": "LRCX", "name": "Lam Research", "sector": "Technology", "weight": 120},
    {"ticker": "PANW", "name": "Palo Alto", "sector": "Technology", "weight": 110},
    {"ticker": "SNPS", "name": "Synopsys", "sector": "Technology", "weight": 95},
    {"ticker": "KLAC", "name": "KLA", "sector": "Technology", "weight": 95},
    {"ticker": "CDNS", "name": "Cadence", "sector": "Technology", "weight": 85},
    {"ticker": "ROP", "name": "Roper", "sector": "Technology", "weight": 60},
    {"ticker": "APH", "name": "Amphenol", "sector": "Technology", "weight": 70},
    {"ticker": "NXPI", "name": "NXP Semi", "sector": "Technology", "weight": 65},
    {"ticker": "ADSK", "name": "Autodesk", "sector": "Technology", "weight": 60},
    {"ticker": "MCHP", "name": "Microchip", "sector": "Technology", "weight": 50},
    {"ticker": "ON", "name": "ON Semi", "sector": "Technology", "weight": 40},
    {"ticker": "FTNT", "name": "Fortinet", "sector": "Technology", "weight": 55},
    {"ticker": "TEL", "name": "TE Connectivity", "sector": "Technology", "weight": 45},
    {"ticker": "MSI", "name": "Motorola", "sector": "Technology", "weight": 55},
    {"ticker": "HPQ", "name": "HP Inc.", "sector": "Technology", "weight": 30},
    {"ticker": "HPE", "name": "HP Ent.", "sector": "Technology", "weight": 25},
    {"ticker": "STX", "name": "Seagate", "sector": "Technology", "weight": 20},
    {"ticker": "WDC", "name": "Western Dig", "sector": "Technology", "weight": 20},
    {"ticker": "NTAP", "name": "NetApp", "sector": "Technology", "weight": 22},
    {"ticker": "FICO", "name": "Fair Isaac", "sector": "Technology", "weight": 40},
    {"ticker": "KEYS", "name": "Keysight", "sector": "Technology", "weight": 25},
    {"ticker": "TER", "name": "Teradyne", "sector": "Technology", "weight": 18},
    {"ticker": "ENPH", "name": "Enphase", "sector": "Technology", "weight": 15},
    {"ticker": "FSLR", "name": "First Solar", "sector": "Technology", "weight": 20},
    {"ticker": "SWKS", "name": "Skyworks", "sector": "Technology", "weight": 15},
    {"ticker": "QRVO", "name": "Qorvo", "sector": "Technology", "weight": 10},
    {"ticker": "AKAM", "name": "Akamai", "sector": "Technology", "weight": 14},

    # --- Communication Services ---
    {"ticker": "GOOGL", "name": "Alphabet A", "sector": "Communication Services", "weight": 3500},
    {"ticker": "META", "name": "Meta", "sector": "Communication Services", "weight": 1300},
    {"ticker": "NFLX", "name": "Netflix", "sector": "Communication Services", "weight": 300},
    {"ticker": "DIS", "name": "Disney", "sector": "Communication Services", "weight": 180},
    {"ticker": "CMCSA", "name": "Comcast", "sector": "Communication Services", "weight": 150},
    {"ticker": "TMUS", "name": "T-Mobile", "sector": "Communication Services", "weight": 200},
    {"ticker": "VZ", "name": "Verizon", "sector": "Communication Services", "weight": 170},
    {"ticker": "T", "name": "AT&T", "sector": "Communication Services", "weight": 130},
    {"ticker": "CHTR", "name": "Charter", "sector": "Communication Services", "weight": 60},
    {"ticker": "EA", "name": "Electronic Arts", "sector": "Communication Services", "weight": 40},
    {"ticker": "WBD", "name": "Warner Bros", "sector": "Communication Services", "weight": 20},
    {"ticker": "TTWO", "name": "Take-Two", "sector": "Communication Services", "weight": 30},
    {"ticker": "OMC", "name": "Omnicom", "sector": "Communication Services", "weight": 20},
    {"ticker": "FOXA", "name": "Fox Corp A", "sector": "Communication Services", "weight": 15},
    {"ticker": "FOX", "name": "Fox Corp B", "sector": "Communication Services", "weight": 14},
    {"ticker": "MTCH", "name": "Match Group", "sector": "Communication Services", "weight": 10},
    {"ticker": "LYV", "name": "Live Nation", "sector": "Communication Services", "weight": 20},
    {"ticker": "LUMN", "name": "Lumen Tech", "sector": "Communication Services", "weight": 2},

    # --- Financial Services ---
    {"ticker": "BRK-B", "name": "Berkshire", "sector": "Financial Services", "weight": 900},
    {"ticker": "JPM", "name": "JPMorgan", "sector": "Financial Services", "weight": 600},
    {"ticker": "V", "name": "Visa", "sector": "Financial Services", "weight": 550},
    {"ticker": "MA", "name": "Mastercard", "sector": "Financial Services", "weight": 450},
    {"ticker": "BAC", "name": "Bank of Amer", "sector": "Financial Services", "weight": 300},
    {"ticker": "WFC", "name": "Wells Fargo", "sector": "Financial Services", "weight": 220},
    {"ticker": "MS", "name": "Morgan Stan", "sector": "Financial Services", "weight": 160},
    {"ticker": "GS", "name": "Goldman", "sector": "Financial Services", "weight": 150},
    {"ticker": "AXP", "name": "Amex", "sector": "Financial Services", "weight": 170},
    {"ticker": "SPGI", "name": "S&P Global", "sector": "Financial Services", "weight": 150},
    {"ticker": "BLK", "name": "BlackRock", "sector": "Financial Services", "weight": 120},
    {"ticker": "C", "name": "Citigroup", "sector": "Financial Services", "weight": 110},
    {"ticker": "CB", "name": "Chubb", "sector": "Financial Services", "weight": 110},
    {"ticker": "PGR", "name": "Progressive", "sector": "Financial Services", "weight": 100},
    {"ticker": "ICE", "name": "Intercont", "sector": "Financial Services", "weight": 80},
    {"ticker": "CME", "name": "CME Group", "sector": "Financial Services", "weight": 75},
    {"ticker": "AON", "name": "Aon", "sector": "Financial Services", "weight": 70},
    {"ticker": "USB", "name": "US Bancorp", "sector": "Financial Services", "weight": 70},
    {"ticker": "PNC", "name": "PNC Fin", "sector": "Financial Services", "weight": 65},
    {"ticker": "TRV", "name": "Travelers", "sector": "Financial Services", "weight": 50},
    {"ticker": "TFC", "name": "Truist", "sector": "Financial Services", "weight": 50},
    {"ticker": "COF", "name": "Capital One", "sector": "Financial Services", "weight": 55},
    {"ticker": "MCO", "name": "Moody's", "sector": "Financial Services", "weight": 80},
    {"ticker": "PYPL", "name": "PayPal", "sector": "Financial Services", "weight": 70},
    {"ticker": "BK", "name": "BNY Mellon", "sector": "Financial Services", "weight": 45},
    {"ticker": "MET", "name": "MetLife", "sector": "Financial Services", "weight": 40},
    {"ticker": "PRU", "name": "Prudential", "sector": "Financial Services", "weight": 35},
    {"ticker": "MSCI", "name": "MSCI", "sector": "Financial Services", "weight": 45},
    {"ticker": "AJG", "name": "Gallagher", "sector": "Financial Services", "weight": 50},
    {"ticker": "AMP", "name": "Ameriprise", "sector": "Financial Services", "weight": 40},
    {"ticker": "SCHW", "name": "Schwab", "sector": "Financial Services", "weight": 130},
    {"ticker": "AFL", "name": "Aflac", "sector": "Financial Services", "weight": 40},
    {"ticker": "ALL", "name": "Allstate", "sector": "Financial Services", "weight": 45},
    {"ticker": "BEN", "name": "Franklin Res", "sector": "Financial Services", "weight": 10},
    {"ticker": "TROW", "name": "T. Rowe Price", "sector": "Financial Services", "weight": 25},
    {"ticker": "FITB", "name": "Fifth Third", "sector": "Financial Services", "weight": 25},
    {"ticker": "KEY", "name": "KeyCorp", "sector": "Financial Services", "weight": 15},
    {"ticker": "RF", "name": "Regions Fin", "sector": "Financial Services", "weight": 20},
    {"ticker": "MTB", "name": "M&T Bank", "sector": "Financial Services", "weight": 25},
    {"ticker": "SYF", "name": "Synchrony", "sector": "Financial Services", "weight": 18},
    {"ticker": "IBKR", "name": "Interactive B", "sector": "Financial Services", "weight": 45},

    # --- Healthcare ---
    {"ticker": "LLY", "name": "Eli Lilly", "sector": "Healthcare", "weight": 800},
    {"ticker": "UNH", "name": "UnitedHealth", "sector": "Healthcare", "weight": 500},
    {"ticker": "JNJ", "name": "J&J", "sector": "Healthcare", "weight": 400},
    {"ticker": "MRK", "name": "Merck", "sector": "Healthcare", "weight": 330},
    {"ticker": "ABBV", "name": "AbbVie", "sector": "Healthcare", "weight": 320},
    {"ticker": "TMO", "name": "Thermo Fisher", "sector": "Healthcare", "weight": 230},
    {"ticker": "ABT", "name": "Abbott", "sector": "Healthcare", "weight": 200},
    {"ticker": "DHR", "name": "Danaher", "sector": "Healthcare", "weight": 180},
    {"ticker": "PFE", "name": "Pfizer", "sector": "Healthcare", "weight": 170},
    {"ticker": "AMGN", "name": "Amgen", "sector": "Healthcare", "weight": 160},
    {"ticker": "ISRG", "name": "Intuitive", "sector": "Healthcare", "weight": 160},
    {"ticker": "SYK", "name": "Stryker", "sector": "Healthcare", "weight": 140},
    {"ticker": "ELV", "name": "Elevance", "sector": "Healthcare", "weight": 130}, 
    {"ticker": "VRTX", "name": "Vertex", "sector": "Healthcare", "weight": 120},
    {"ticker": "REGN", "name": "Regeneron", "sector": "Healthcare", "weight": 110},
    {"ticker": "HCA", "name": "HCA Health", "sector": "Healthcare", "weight": 90},
    {"ticker": "BSX", "name": "Boston Sci", "sector": "Healthcare", "weight": 110},
    {"ticker": "BDX", "name": "Becton Dick", "sector": "Healthcare", "weight": 70},
    {"ticker": "GILD", "name": "Gilead", "sector": "Healthcare", "weight": 80},
    {"ticker": "ZTS", "name": "Zoetis", "sector": "Healthcare", "weight": 85},
    {"ticker": "CI", "name": "Cigna", "sector": "Healthcare", "weight": 95},
    {"ticker": "MCK", "name": "McKesson", "sector": "Healthcare", "weight": 70},
    {"ticker": "BMY", "name": "Bristol-Myers", "sector": "Healthcare", "weight": 90},
    {"ticker": "CVS", "name": "CVS Health", "sector": "Healthcare", "weight": 80},
    {"ticker": "COR", "name": "Cencora", "sector": "Healthcare", "weight": 50},
    {"ticker": "MDT", "name": "Medtronic", "sector": "Healthcare", "weight": 110},
    {"ticker": "EW", "name": "Edwards Life", "sector": "Healthcare", "weight": 40},
    {"ticker": "IQV", "name": "IQVIA", "sector": "Healthcare", "weight": 45},
    {"ticker": "IDXX", "name": "IDEXX", "sector": "Healthcare", "weight": 40},
    {"ticker": "HUM", "name": "Humana", "sector": "Healthcare", "weight": 40},
    {"ticker": "DXCM", "name": "Dexcom", "sector": "Healthcare", "weight": 35},
    {"ticker": "BIO", "name": "Bio-Rad", "sector": "Healthcare", "weight": 8},
    {"ticker": "A", "name": "Agilent", "sector": "Healthcare", "weight": 40},
    {"ticker": "WAT", "name": "Waters", "sector": "Healthcare", "weight": 18},
    {"ticker": "STE", "name": "Steris", "sector": "Healthcare", "weight": 22},
    {"ticker": "RMD", "name": "ResMed", "sector": "Healthcare", "weight": 25},
    {"ticker": "CNC", "name": "Centene", "sector": "Healthcare", "weight": 35},
    {"ticker": "EXAS", "name": "Exact Sci", "sector": "Healthcare", "weight": 10},
    {"ticker": "MRNA", "name": "Moderna", "sector": "Healthcare", "weight": 25},
    {"ticker": "BIIB", "name": "Biogen", "sector": "Healthcare", "weight": 30},
    {"ticker": "ALGN", "name": "Align Tech", "sector": "Healthcare", "weight": 18},

    # --- Consumer Cyclical ---
    {"ticker": "AMZN", "name": "Amazon", "sector": "Consumer Cyclical", "weight": 2000},
    {"ticker": "TSLA", "name": "Tesla", "sector": "Consumer Cyclical", "weight": 700},
    {"ticker": "HD", "name": "Home Depot", "sector": "Consumer Cyclical", "weight": 380},
    {"ticker": "MCD", "name": "McDonald's", "sector": "Consumer Cyclical", "weight": 210},
    {"ticker": "NKE", "name": "Nike", "sector": "Consumer Cyclical", "weight": 150},
    {"ticker": "SBUX", "name": "Starbucks", "sector": "Consumer Cyclical", "weight": 110},
    {"ticker": "LOW", "name": "Lowe's", "sector": "Consumer Cyclical", "weight": 140},
    {"ticker": "BKNG", "name": "Booking", "sector": "Consumer Cyclical", "weight": 130},
    {"ticker": "TJX", "name": "TJX", "sector": "Consumer Cyclical", "weight": 120},
    {"ticker": "F", "name": "Ford", "sector": "Consumer Cyclical", "weight": 50},
    {"ticker": "GM", "name": "GM", "sector": "Consumer Cyclical", "weight": 55},
    {"ticker": "MAR", "name": "Marriott", "sector": "Consumer Cyclical", "weight": 70},
    {"ticker": "ORLY", "name": "O'Reilly", "sector": "Consumer Cyclical", "weight": 65},
    {"ticker": "CMG", "name": "Chipotle", "sector": "Consumer Cyclical", "weight": 80},
    {"ticker": "HLT", "name": "Hilton", "sector": "Consumer Cyclical", "weight": 50},
    {"ticker": "ROST", "name": "Ross", "sector": "Consumer Cyclical", "weight": 50},
    {"ticker": "DHI", "name": "DR Horton", "sector": "Consumer Cyclical", "weight": 50},
    {"ticker": "LEN", "name": "Lennar", "sector": "Consumer Cyclical", "weight": 45},
    {"ticker": "EBAY", "name": "eBay", "sector": "Consumer Cyclical", "weight": 30},
    {"ticker": "YUM", "name": "Yum! Brands", "sector": "Consumer Cyclical", "weight": 38},
    {"ticker": "AZO", "name": "AutoZone", "sector": "Consumer Cyclical", "weight": 55},
    {"ticker": "TSCO", "name": "Tractor Supply", "sector": "Consumer Cyclical", "weight": 30},
    {"ticker": "GPC", "name": "Genuine Parts", "sector": "Consumer Cyclical", "weight": 20},
    {"ticker": "BBY", "name": "Best Buy", "sector": "Consumer Cyclical", "weight": 18},
    {"ticker": "PHM", "name": "PulteGroup", "sector": "Consumer Cyclical", "weight": 25},
    {"ticker": "VFC", "name": "VF Corp", "sector": "Consumer Cyclical", "weight": 6},
    {"ticker": "RL", "name": "Ralph Lauren", "sector": "Consumer Cyclical", "weight": 10},
    {"ticker": "WHR", "name": "Whirlpool", "sector": "Consumer Cyclical", "weight": 5},
    {"ticker": "HAS", "name": "Hasbro", "sector": "Consumer Cyclical", "weight": 8},
    {"ticker": "MAT", "name": "Mattel", "sector": "Consumer Cyclical", "weight": 6},
    {"ticker": "TPR", "name": "Tapestry", "sector": "Consumer Cyclical", "weight": 10},
    {"ticker": "GRMN", "name": "Garmin", "sector": "Consumer Cyclical", "weight": 30},
    {"ticker": "LVS", "name": "Las Vegas Sands", "sector": "Consumer Cyclical", "weight": 35},
    {"ticker": "MGM", "name": "MGM Resorts", "sector": "Consumer Cyclical", "weight": 15},
    {"ticker": "CPRI", "name": "Capri", "sector": "Consumer Cyclical", "weight": 5},

    # --- Consumer Defensive ---
    {"ticker": "WMT", "name": "Walmart", "sector": "Consumer Defensive", "weight": 550},
    {"ticker": "PG", "name": "P&G", "sector": "Consumer Defensive", "weight": 400},
    {"ticker": "COST", "name": "Costco", "sector": "Consumer Defensive", "weight": 380},
    {"ticker": "KO", "name": "Coca-Cola", "sector": "Consumer Defensive", "weight": 280},
    {"ticker": "PEP", "name": "PepsiCo", "sector": "Consumer Defensive", "weight": 240},
    {"ticker": "PM", "name": "Philip Morris", "sector": "Consumer Defensive", "weight": 160},
    {"ticker": "MDLZ", "name": "Mondelez", "sector": "Consumer Defensive", "weight": 100},
    {"ticker": "MO", "name": "Altria", "sector": "Consumer Defensive", "weight": 80},
    {"ticker": "TGT", "name": "Target", "sector": "Consumer Defensive", "weight": 75},
    {"ticker": "CL", "name": "Colgate", "sector": "Consumer Defensive", "weight": 70},
    {"ticker": "KMB", "name": "Kimberly-Clark", "sector": "Consumer Defensive", "weight": 45},
    {"ticker": "GIS", "name": "General Mills", "sector": "Consumer Defensive", "weight": 40},
    {"ticker": "SYY", "name": "Sysco", "sector": "Consumer Defensive", "weight": 40},
    {"ticker": "EL", "name": "Estee Lauder", "sector": "Consumer Defensive", "weight": 35},
    {"ticker": "KR", "name": "Kroger", "sector": "Consumer Defensive", "weight": 40},
    {"ticker": "ADM", "name": "Archer-Dan", "sector": "Consumer Defensive", "weight": 30},
    {"ticker": "TSN", "name": "Tyson Foods", "sector": "Consumer Defensive", "weight": 20},
    {"ticker": "HSY", "name": "Hershey", "sector": "Consumer Defensive", "weight": 38},
    {"ticker": "STZ", "name": "Constellation", "sector": "Consumer Defensive", "weight": 50},
    {"ticker": "MNST", "name": "Monster Bev", "sector": "Consumer Defensive", "weight": 55},
    {"ticker": "CHD", "name": "Church \u0026 Dwight", "sector": "Consumer Defensive", "weight": 25},
    {"ticker": "CLX", "name": "Clorox", "sector": "Consumer Defensive", "weight": 18},
    {"ticker": "MKC", "name": "McCormick", "sector": "Consumer Defensive", "weight": 18},
    {"ticker": "HRL", "name": "Hormel", "sector": "Consumer Defensive", "weight": 15},
    {"ticker": "CPB", "name": "Campbell Soup", "sector": "Consumer Defensive", "weight": 12},
    {"ticker": "SJM", "name": "Smucker", "sector": "Consumer Defensive", "weight": 12},
    {"ticker": "TAP", "name": "Molson Coors", "sector": "Consumer Defensive", "weight": 12},
    {"ticker": "CAG", "name": "Conagra", "sector": "Consumer Defensive", "weight": 15},

    # --- Energy ---
    {"ticker": "XOM", "name": "Exxon", "sector": "Energy", "weight": 500},
    {"ticker": "CVX", "name": "Chevron", "sector": "Energy", "weight": 300},
    {"ticker": "COP", "name": "ConocoPhillips", "sector": "Energy", "weight": 140},
    {"ticker": "SLB", "name": "Schlumberger", "sector": "Energy", "weight": 85},
    {"ticker": "EOG", "name": "EOG Res", "sector": "Energy", "weight": 75},
    {"ticker": "MPC", "name": "Marathon", "sector": "Energy", "weight": 65},
    {"ticker": "VLO", "name": "Valero", "sector": "Energy", "weight": 55},
    {"ticker": "PSX", "name": "Phillips 66", "sector": "Energy", "weight": 60},
    {"ticker": "OXY", "name": "Occidental", "sector": "Energy", "weight": 55},
    {"ticker": "KMI", "name": "Kinder Morgan", "sector": "Energy", "weight": 40},
    {"ticker": "WMB", "name": "Williams", "sector": "Energy", "weight": 45},
    {"ticker": "HAL", "name": "Halliburton", "sector": "Energy", "weight": 35},
    {"ticker": "DVN", "name": "Devon Energy", "sector": "Energy", "weight": 25},
    {"ticker": "OKE", "name": "ONEOK", "sector": "Energy", "weight": 40},
    {"ticker": "CTRA", "name": "Coterra", "sector": "Energy", "weight": 20},
    {"ticker": "FANG", "name": "Diamondback", "sector": "Energy", "weight": 35},
    {"ticker": "APA", "name": "APA Corp", "sector": "Energy", "weight": 10},
    {"ticker": "BKR", "name": "Baker Hughes", "sector": "Energy", "weight": 35},

    # --- Industrials ---
    {"ticker": "CAT", "name": "Caterpillar", "sector": "Industrials", "weight": 180},
    {"ticker": "GE", "name": "GE", "sector": "Industrials", "weight": 180},
    {"ticker": "UNP", "name": "Union Pacific", "sector": "Industrials", "weight": 160},
    {"ticker": "HON", "name": "Honeywell", "sector": "Industrials", "weight": 140},
    {"ticker": "RTX", "name": "Raytheon", "sector": "Industrials", "weight": 140},
    {"ticker": "UPS", "name": "UPS", "sector": "Industrials", "weight": 120},
    {"ticker": "LMT", "name": "Lockheed", "sector": "Industrials", "weight": 110},
    {"ticker": "BA", "name": "Boeing", "sector": "Industrials", "weight": 110},
    {"ticker": "DE", "name": "Deere", "sector": "Industrials", "weight": 110},
    {"ticker": "ADP", "name": "ADP", "sector": "Industrials", "weight": 100},
    {"ticker": "ETN", "name": "Eaton", "sector": "Industrials", "weight": 130},
    {"ticker": "ITW", "name": "Illinois Tool", "sector": "Industrials", "weight": 80},
    {"ticker": "GD", "name": "General Dyn", "sector": "Industrials", "weight": 80},
    {"ticker": "NOC", "name": "Northrop", "sector": "Industrials", "weight": 70},
    {"ticker": "WM", "name": "Waste Mgmt", "sector": "Industrials", "weight": 85},
    {"ticker": "CSX", "name": "CSX", "sector": "Industrials", "weight": 70},
    {"ticker": "NSC", "name": "Norfolk", "sector": "Industrials", "weight": 55},
    {"ticker": "EMR", "name": "Emerson", "sector": "Industrials", "weight": 65},
    {"ticker": "MMM", "name": "3M", "sector": "Industrials", "weight": 60},
    {"ticker": "FDX", "name": "FedEx", "sector": "Industrials", "weight": 65},
    {"ticker": "CARR", "name": "Carrier", "sector": "Industrials", "weight": 55},
    {"ticker": "FAST", "name": "Fastenal", "sector": "Industrials", "weight": 40},
    {"ticker": "PH", "name": "Parker-Hannifin", "sector": "Industrials", "weight": 70},
    {"ticker": "GWW", "name": "Grainger", "sector": "Industrials", "weight": 45},
    {"ticker": "AME", "name": "Ametek", "sector": "Industrials", "weight": 40},
    {"ticker": "OTIS", "name": "Otis", "sector": "Industrials", "weight": 40},
    {"ticker": "PCAR", "name": "PACCAR", "sector": "Industrials", "weight": 35},
    {"ticker": "RSG", "name": "Republic Svcs", "sector": "Industrials", "weight": 60},
    {"ticker": "IR", "name": "Ingersoll Rand", "sector": "Industrials", "weight": 35},
    {"ticker": "CPRT", "name": "Copart", "sector": "Industrials", "weight": 50},
    {"ticker": "EFX", "name": "Equifax", "sector": "Industrials", "weight": 30},
    {"ticker": "PAYX", "name": "Paychex", "sector": "Industrials", "weight": 45},
    {"ticker": "CTAS", "name": "Cintas", "sector": "Industrials", "weight": 65},
    {"ticker": "VRSK", "name": "Verisk", "sector": "Industrials", "weight": 40},
    {"ticker": "DOV", "name": "Dover", "sector": "Industrials", "weight": 25},
    {"ticker": "ODFL", "name": "Old Dominion", "sector": "Industrials", "weight": 45},
    {"ticker": "JBHT", "name": "JB Hunt", "sector": "Industrials", "weight": 18},
    {"ticker": "TXT", "name": "Textron", "sector": "Industrials", "weight": 18},
    {"ticker": "HWM", "name": "Howmet", "sector": "Industrials", "weight": 35},

    # --- Utilities ---
    {"ticker": "NEE", "name": "NextEra", "sector": "Utilities", "weight": 130},
    {"ticker": "SO", "name": "Southern", "sector": "Utilities", "weight": 90},
    {"ticker": "DUK", "name": "Duke Energy", "sector": "Utilities", "weight": 85},
    {"ticker": "SRE", "name": "Sempra", "sector": "Utilities", "weight": 50},
    {"ticker": "AEP", "name": "American Elec", "sector": "Utilities", "weight": 50},
    {"ticker": "D", "name": "Dominion", "sector": "Utilities", "weight": 45},
    {"ticker": "PEG", "name": "Public Ent", "sector": "Utilities", "weight": 40},
    {"ticker": "PCG", "name": "PG\u0026E", "sector": "Utilities", "weight": 45},
    {"ticker": "EXC", "name": "Exelon", "sector": "Utilities", "weight": 40},
    {"ticker": "ED", "name": "Consol Edison", "sector": "Utilities", "weight": 35},
    {"ticker": "XEL", "name": "Xcel Energy", "sector": "Utilities", "weight": 35},
    {"ticker": "WEC", "name": "WEC Energy", "sector": "Utilities", "weight": 30},
    {"ticker": "AWK", "name": "American Water", "sector": "Utilities", "weight": 25},
    {"ticker": "EIX", "name": "Edison Int", "sector": "Utilities", "weight": 30},
    {"ticker": "DTE", "name": "DTE Energy", "sector": "Utilities", "weight": 28},
    {"ticker": "ES", "name": "Evergy", "sector": "Utilities", "weight": 25},
    {"ticker": "FE", "name": "FirstEnergy", "sector": "Utilities", "weight": 22},
    {"ticker": "LNT", "name": "Alliant", "sector": "Utilities", "weight": 14},
    {"ticker": "ATO", "name": "Atmos Energy", "sector": "Utilities", "weight": 18},
    {"ticker": "CMS", "name": "CMS Energy", "sector": "Utilities", "weight": 18},
    {"ticker": "CNP", "name": "CenterPoint", "sector": "Utilities", "weight": 18},
    {"ticker": "NI", "name": "NiSource", "sector": "Utilities", "weight": 12},

    # --- Real Estate ---
    {"ticker": "PLD", "name": "Prologis", "sector": "Real Estate", "weight": 120},
    {"ticker": "AMT", "name": "Amer Tower", "sector": "Real Estate", "weight": 90},
    {"ticker": "EQIX", "name": "Equinix", "sector": "Real Estate", "weight": 80},
    {"ticker": "WELL", "name": "Welltower", "sector": "Real Estate", "weight": 60},
    {"ticker": "PSA", "name": "Public Storage", "sector": "Real Estate", "weight": 50},
    {"ticker": "CCI", "name": "Crown Castle", "sector": "Real Estate", "weight": 45},
    {"ticker": "O", "name": "Realty Income", "sector": "Real Estate", "weight": 50},
    {"ticker": "SPG", "name": "Simon Prop", "sector": "Real Estate", "weight": 50},
    {"ticker": "DLR", "name": "Digital Realty", "sector": "Real Estate", "weight": 45},
    {"ticker": "BX", "name": "Blackstone", "sector": "Real Estate", "weight": 140},
    {"ticker": "CBRE", "name": "CBRE Group", "sector": "Real Estate", "weight": 25},
    {"ticker": "VICI", "name": "VICI Prop", "sector": "Real Estate", "weight": 30},
    {"ticker": "SBAC", "name": "SBA Comm", "sector": "Real Estate", "weight": 25},
    {"ticker": "WY", "name": "Weyerhaeuser", "sector": "Real Estate", "weight": 25},
    {"ticker": "ARE", "name": "Alexandria", "sector": "Real Estate", "weight": 20},
    {"ticker": "AVB", "name": "AvalonBay", "sector": "Real Estate", "weight": 30},
    {"ticker": "EQR", "name": "Equity Resid", "sector": "Real Estate", "weight": 25},
    {"ticker": "VRE", "name": "Veris", "sector": "Real Estate", "weight": 5},
    {"ticker": "HST", "name": "Host Hotels", "sector": "Real Estate", "weight": 12},
    {"ticker": "MAA", "name": "Mid-America", "sector": "Real Estate", "weight": 18},
    {"ticker": "UDR", "name": "UDR Inc.", "sector": "Real Estate", "weight": 12},
    {"ticker": "BXP", "name": "Boston Prop", "sector": "Real Estate", "weight": 15},
    {"ticker": "REG", "name": "Regency", "sector": "Real Estate", "weight": 10},
    {"ticker": "KIM", "name": "Kimco", "sector": "Real Estate", "weight": 12},

    # --- Basic Materials ---
    {"ticker": "LIN", "name": "Linde", "sector": "Basic Materials", "weight": 220},
    {"ticker": "SHW", "name": "Sherwin", "sector": "Basic Materials", "weight": 80},
    {"ticker": "FCX", "name": "Freeport", "sector": "Basic Materials", "weight": 70},
    {"ticker": "APD", "name": "Air Products", "sector": "Basic Materials", "weight": 60},
    {"ticker": "ECL", "name": "Ecolab", "sector": "Basic Materials", "weight": 65},
    {"ticker": "NEM", "name": "Newmont", "sector": "Basic Materials", "weight": 50},
    {"ticker": "CTVA", "name": "Corteva", "sector": "Basic Materials", "weight": 40},
    {"ticker": "DOW", "name": "Dow Inc.", "sector": "Basic Materials", "weight": 40},
    {"ticker": "NUE", "name": "Nucor", "sector": "Basic Materials", "weight": 45},
    {"ticker": "ALB", "name": "Albemarle", "sector": "Basic Materials", "weight": 15},
    {"ticker": "MLM", "name": "Martin Mar.", "sector": "Basic Materials", "weight": 35},
    {"ticker": "VMC", "name": "Vulcan Mat.", "sector": "Basic Materials", "weight": 35},
    {"ticker": "PPG", "name": "PPG Industries", "sector": "Basic Materials", "weight": 35},
    {"ticker": "DD", "name": "DuPont", "sector": "Basic Materials", "weight": 35},
    {"ticker": "LYB", "name": "LyondellBasell", "sector": "Basic Materials", "weight": 30},
    {"ticker": "EMN", "name": "Eastman", "sector": "Basic Materials", "weight": 12},
    {"ticker": "MOS", "name": "Mosaic", "sector": "Basic Materials", "weight": 10},
    {"ticker": "FMC", "name": "FMC Corp", "sector": "Basic Materials", "weight": 8},
    {"ticker": "CF", "name": "CF Industries", "sector": "Basic Materials", "weight": 15},
    {"ticker": "CE", "name": "Celanese", "sector": "Basic Materials", "weight": 15},
    {"ticker": "PKG", "name": "Packaging Corp", "sector": "Basic Materials", "weight": 18},
    {"ticker": "IFF", "name": "Intl Flavors", "sector": "Basic Materials", "weight": 20},
    {"ticker": "SEE", "name": "Sealed Air", "sector": "Basic Materials", "weight": 8},
]
